# Définit la version de Docker Compose
version: '3.9'

# Définit les services de l'application
services:
  # Service web
  web:
    # Construit le service à partir du Dockerfile spécifié
    build:
      context: .  # Contexte de construction (répertoire actuel)
      dockerfile: docker/php/Dockerfile  # Chemin vers le Dockerfile
    container_name: docker_ssb_web  # Nom du conteneur
    ports:
      - '8080:80'  # Redirige le port 8080 de l'hôte vers le port 80 du conteneur
    volumes:
      - ./:/var/www/html  # Montez le répertoire actuel sur /var/www/html dans le conteneur

  # Service de base de données
  database:
    image: mariadb:latest  # Utilise l'image MariaDB la plus récente
    restart: always  # Redémarre toujours le conteneur si celui-ci s'arrête
    environment:
      MARIADB_ROOT_PASSWORD: root  # Définit le mot de passe root de MariaDB
    volumes:
      - ssb_database:/var/lib/mysql  # Montez le volume ssb_database sur /var/lib/mysql dans le conteneur
    ports:
      - "33306:3306"  # Redirige le port 33306 de l'hôte vers le port 3306 du conteneur

  # Service RabbitMQ
  rabbitmq:
    image: rabbitmq:management  # Utilise l'image RabbitMQ avec l'interface de gestion
    container_name: ssb_rabbitmq  # Nom du conteneur
    ports:
      - '5672:5672'  # Port pour la communication AMQP
      - '15672:15672'  # Port pour l'interface de gestion web
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq  # Montez un volume pour persister les données

# Définit les volumes utilisés par les services
volumes:
  ssb_database:  # Volume pour la base de données MariaDB
